-- ============================================================================
-- 热搜数据 · 当日新发布榜 · 第 4/4 块（Day 17）
-- ============================================================================
-- 本块 5 条，全部来自 db/seed-hot.sql（由 db/sync_hot.py 生成）
-- 幂等：ON CONFLICT (bvid) DO UPDATE，重复执行不报错
-- 各块之间没有依赖，可以任意顺序执行
-- ============================================================================

INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1E9pb6uEpm', 'fresh', '【东方MMD】在我的世界中直播的琪露诺', '探险家sunrise', 3461568480152156, 268, 0, 15, '0:44', 'MMD·3D', 1791543600, 'https://i2.hdslb.com/bfs/archive/8ad26dbe5b143a73db1e5207c03a97615e0e6fbc.jpg', 'https://www.youtube.com/watch?v=nb3VZRzU0Ik', 'bilibili', 16, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1sBp46rENf', 'fresh', '忒乐忒乐邦邦娜巴拉尼，卡特克贝贝呗…… 植物大战僵尸精华版自制关卡：植僵红魔狂', '饲养员和他的fumo们', 3707023367604668, 413, 3, 7, '18:37', '单机游戏', 1791535414, 'https://i0.hdslb.com/bfs/archive/0fe2c6dec748f0da2df0379e745f8c070a247f79.jpg', 'EX关已做好，基本上就是个BOSS RUSH再加个cos二小姐的无畏者 再优化一下其他一些小细节明天就可以发布了', 'bilibili', 17, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1gpp46QEy5', 'fresh', '【東方Vocal】Die Before Me_竹取飛翔 ～ Lunatic Princess × 月まで届け、不死の煙', '三好市民流龍馬', 3282234, 36, 0, 3, '4:22', '音乐综合', 1791534785, 'https://i0.hdslb.com/bfs/archive/fa330417736362c7f649185455b94887f1e22e0e.jpg', 'youtube www.youtube.com/watch?v=uITvSFufHXQ 原UP：Lunatic Phantasma', 'bilibili', 18, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1VJp469EP7', 'fresh', '当红雾散去，我将亲手为这里献上一颗毁灭菇！ 植物大战僵尸精华版自制关卡：至福乐土洒下血雨', '饲养员和他的fumo们', 3707023367604668, 174, 0, 2, '5:59', '单机游戏', 1791534395, 'https://i0.hdslb.com/bfs/archive/cc571078b947655cb6bbc41cbdf981ee773cc841.jpg', '威！严！ 就当作红魔馆又炸了一回吧', 'bilibili', 19, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1YJp469Evs', 'fresh', '东方红魔乡六面就像：', '钟花束', 487166851, 1375, 3, 35, '0:27', '音乐综合', 1791534119, 'https://i2.hdslb.com/bfs/archive/646b90eb5b4f8d0f4597f301f8eba0481bbe9980.jpg', '感觉副歌太突兀了', 'bilibili', 20, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;

-- 验证：
--   SELECT COUNT(*) FROM hot_videos WHERE board = 'fresh';
