-- ============================================================================
-- 热搜数据 · 当日新发布榜 · 第 2/4 块（Day 17）
-- ============================================================================
-- 本块 5 条，全部来自 db/seed-hot.sql（由 db/sync_hot.py 生成）
-- 幂等：ON CONFLICT (bvid) DO UPDATE，重复执行不报错
-- 各块之间没有依赖，可以任意顺序执行
-- ============================================================================

INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1xhHX6EE3b', 'fresh', '特异Fumo', '五十五开尔文', 700476417, 6, 0, 0, '0:16', 'MV', 1791598200, 'https://i0.hdslb.com/bfs/archive/75b50478bcc20d0bd5d8c2079d209f4508fafd19.jpg', '-', 'bilibili', 6, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1y8pe6FExJ', 'fresh', '【苏州THO】各种杂项存货（无人机飞行&自由舞台）', '蓬莱山辉夜の玉枝', 412954490, 22, 0, 1, '5:30', '搞笑', 1791598139, 'https://i0.hdslb.com/bfs/archive/a35467b262822c8a577a1d8b6f37df73f7f3a0bc.jpg', '2024年的事情了，当时还是在平江府而不是金陵雅X酒店', 'bilibili', 7, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV13Wpb6fEi2', 'fresh', '魂魄妖梦 全符卡 中间禁移动 全避无伤公式演示', '差错之鱼undyne', 397685732, 87, 0, 0, '8:33', '单机游戏', 1791597600, 'https://i1.hdslb.com/bfs/archive/5b3744bc9bcae6d9ed2ef9f6e4b9df7b8259dbb9.jpg', '中间禁移动教 最新力作！！！', 'bilibili', 8, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1epph6ME2h', 'fresh', '全乡最强最冷最高人气最聪明妖精——琪露诺 LNN', 'dandelion233', 3546717368617604, 42, 0, 0, '2:47', '单机游戏', 1791594540, 'https://i0.hdslb.com/bfs/archive/ab2687b0c462d209ef5e0fc53d1989e333820d84.jpg', '新典的baka没有经典的冻牛肉台词了呜呜呜——BGM也变得更符合歌名了，没有之前那种“最强”的感觉，反而变成“最可爱”了(笑)——不过真要论实力的话，最强的妖精目前来看应该还是皮丝吧() 不知道从什么时候开始baka就变成公认底力检测器了，yym和ddc的符都好吃底力，hmx的几张符也挺吃的，嘛，毕竟还是名义上的最强嘛，给点特权很正常 算上baka的好朋友大酱，莉莉白，后续出场的皮丝和拉尔瓦，还有', 'bilibili', 9, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1XMpa6iErH', 'fresh', '[东方红魔乡新典EX] 有一个人前来混关', '浮腻', 3640568, 13, 0, 0, '10:37', '单机游戏', 1791588645, 'https://i2.hdslb.com/bfs/archive/b243ef27a56a61f47447e1a938e327e1c707073c.jpg', '丑陋！打的太丑陋了！', 'bilibili', 10, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;

-- 验证：
--   SELECT COUNT(*) FROM hot_videos WHERE board = 'fresh';
