-- ============================================================================
-- 热搜数据 · 当日新发布榜 · 第 3/4 块（Day 17）
-- ============================================================================
-- 本块 5 条，全部来自 db/seed-hot.sql（由 db/sync_hot.py 生成）
-- 幂等：ON CONFLICT (bvid) DO UPDATE，重复执行不报错
-- 各块之间没有依赖，可以任意顺序执行
-- ============================================================================

INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV117p86QEkn', 'fresh', '如果芙兰朵露的声音换成乌咪', '蓝色少女琪露诺', 3546916042312290, 66, 0, 0, '1:20', '日常', 1791570039, 'https://i1.hdslb.com/bfs/archive/b8f59c266348063ea742d877659fa8b2a73906bf.jpg', '-', 'bilibili', 11, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV117p86QETH', 'fresh', '幻想乡没有巴士！武汉THO痛车区展览区欣赏，从六轮到两轮都有！', 'Im萨姆', 39507722, 563, 4, 6, '1:51', '单机游戏', 1791569939, 'https://i2.hdslb.com/bfs/archive/021a5c5713585b63f77579312ff8e759b761e115.jpg', '武汉tho痛车区实拍！是由奶茶cos的博丽灵梦御地飞行拍的哦（笑） 由武汉景景有约专线合作的悬挂东方tho限定宣传痛版画的营运旅游专线公交车经过几个月又和大家见面了！版画将保持长期留存！ 其他都是各路东方同好的痛车，请大家欣赏，希望大家喜欢。', 'bilibili', 12, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1HTph6EEur', 'fresh', '【东方原作补完计划 - 东方永夜抄】我又被东方永夜抄玩了', '失业の膜法使玳烨', 517829430, 200, 0, 4, '29:40', '单机游戏', 1791562079, 'https://i0.hdslb.com/bfs/archive/1a1dbb4a5d0b44f9a2d263e58f16001923248393.jpg', '求三连 bgm - Sing, R. Sing! - 幼女幻奏', 'bilibili', 13, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1TRpt6SEML', 'fresh', '【东方project】村纱水蜜 在夏天让水鬼们全部沉底了，快谢谢我们的船长', '正在沉睡请勿打扰', 3546797119113789, 101, 0, 5, '1:42', '单机游戏', 1791556199, 'https://i0.hdslb.com/bfs/archive/498d6196be671289a0ff29de8d3ca32233b9534e.jpg', '-', 'bilibili', 14, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1oZpb6vEwZ', 'fresh', '【东方MMD】东方红魔乡 PV', '探险家sunrise', 3461568480152156, 258, 0, 16, '1:54', 'MMD·3D', 1791548400, 'https://i2.hdslb.com/bfs/archive/725dafef8c90ff7d8ea41eef392d28df3a751c36.jpg', 'https://www.youtube.com/watch?v=3ef0EAyiUdg', 'bilibili', 15, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;

-- 验证：
--   SELECT COUNT(*) FROM hot_videos WHERE board = 'fresh';
