-- ============================================================================
-- 热搜数据 · 当日新发布榜 · 第 1/4 块（Day 17）
-- ============================================================================
-- 本块 5 条，全部来自 db/seed-hot.sql（由 db/sync_hot.py 生成）
-- 幂等：ON CONFLICT (bvid) DO UPDATE，重复执行不报错
-- 各块之间没有依赖，可以任意顺序执行
-- ============================================================================

INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV13Wpb6fE79', 'fresh', '魂魄妖梦 ①符 一式「人之剑」中间禁移动 公式', '差错之鱼undyne', 397685732, 0, 0, 0, '0:44', '单机游戏', 1791601200, 'https://i2.hdslb.com/bfs/archive/ad62979920a02885488434afc2903312b89baee3.jpg', '新公式①', 'bilibili', 1, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV19upe6CERA', 'fresh', '星期五的琪露诺', '一行瑠璃吾之妻', 227582511, 0, 0, 0, '0:28', '日常', 1791601183, 'https://i0.hdslb.com/bfs/archive/841de67e1aea844d9319d6e7e7612c4c9202a79c.jpg', 'https://x.com/TheDailyFUMO/status/2108371429490094103', 'bilibili', 2, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1wXpY6xE7M', 'fresh', '东方风神录 东风谷早苗HNN', '藤导磁', 690922530, 2, 0, 0, '2:4', '单机游戏', 1791599996, 'https://i1.hdslb.com/bfs/archive/03bfbbd82f74140ef55ab9606230a18eec1e4120.jpg', '', 'bilibili', 3, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1fFpe6SENM', 'fresh', '东方绀珠传Lunatic 早苗10MNB', '記憶偽筆', 67808865, 8, 0, 0, '33:43', '单机游戏', 1791599788, 'https://i0.hdslb.com/bfs/archive/7d6379451ee31aedc6d31d06263fa9a998ac2836.jpg', '', 'bilibili', 4, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1owpe6EE4v', 'fresh', '[武汉tho]可观测宇宙内阿麟浓度最高的地方', '阿卡麟不会被遗忘', 170209535, 56, 0, 1, '0:26', 'MMD·3D', 1791599257, 'https://i0.hdslb.com/bfs/archive/471d44d7c7120d27fe49d9498352dab708bd4fb9.jpg', '-', 'bilibili', 5, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;

-- 验证：
--   SELECT COUNT(*) FROM hot_videos WHERE board = 'fresh';
