-- ============================================================================
-- 热搜数据 · 历史热门榜 · 第 3/4 块（Day 17）
-- ============================================================================
-- 本块 5 条，全部来自 db/seed-hot.sql（由 db/sync_hot.py 生成）
-- 幂等：ON CONFLICT (bvid) DO UPDATE，重复执行不报错
-- 各块之间没有依赖，可以任意顺序执行
-- ============================================================================

INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1f9gCzhEKn', 'hot', '【東方MMD】咲夜 -stickysticky', 'Silent-Sliver', 28687790, 269939, 373, 19422, '3:34', 'MMD·3D', 1751291231, 'https://i2.hdslb.com/bfs/archive/c51c9963e16b092e562d63a21ab31c62691d6c96.jpg', '可以限流，就算限流到只有关注我的粉丝才能看到也可以，但请至少让我过审，谢谢，B站有未成年模式，我的视频不会对其有影响的', 'bilibili', 11, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1qWaS6QEXh', 'hot', '游戏试玩 东方绀珠传', '刃手堂Switch2', 1189268743, 219550, 117, 2671, '1:19', '单机游戏', 1790937000, 'https://i0.hdslb.com/bfs/archive/0ffcd7a27b904afa15048b7eae09eeb7d490d241.jpg', '', 'bilibili', 12, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1ws411A7BC', 'hot', '【东方红魔乡】原作全剧情+对话', '南极冻鱼', 69768372, 198858, 1605, 8479, '22:44', '单机游戏', 1532611143, 'https://i0.hdslb.com/bfs/archive/8a008908d0297bf3699c9b8ca20e2b1ea9145f6c.jpg', '(无结局) 幻想乡迎来了未曾预料的热闹日子。 在神秘的来访者看来，好像连夏天的亡灵都会迷惘。 就在那样的很普通的夏天。 边境被红色的幻想包围了。 * 前言和人物介绍来自游戏自带文案 * 初次投稿 有不对的地方请指出TAT', 'bilibili', 13, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1RoY46REkt', 'hot', '东方红魔乡：新典全bgm（已全更新）', '蒲风千晴', 419740037, 182788, 775, 3581, '59:48', '日常', 1788967380, 'https://i1.hdslb.com/bfs/archive/a2d7745ded4f0d24de0db73496dbe03d8fe0338f.jpg', '东方红魔乡：新典全bgm 至此全部更新完毕 下个东方视频应该就是鬼形兽全收集了 这半年应该能出来 大概吧（ 要不当中先做个杂谈水一期（）', 'bilibili', 14, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1Jz4y1U7jc', 'hot', '东方永夜抄全bgm收集+角色图', '蒲风千晴', 419740037, 179370, 1365, 3226, '83:0', '电台', 1612520444, 'https://i0.hdslb.com/bfs/archive/528560d2109799977cc007eecf77fea764a4d142.jpg', '东方永夜抄全音乐收集，达成', 'bilibili', 15, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;

-- 验证：
--   SELECT COUNT(*) FROM hot_videos WHERE board = 'hot';
