-- ============================================================================
-- 热搜数据 · 历史热门榜 · 第 2/4 块（Day 17）
-- ============================================================================
-- 本块 5 条，全部来自 db/seed-hot.sql（由 db/sync_hot.py 生成）
-- 幂等：ON CONFLICT (bvid) DO UPDATE，重复执行不报错
-- 各块之间没有依赖，可以任意顺序执行
-- ============================================================================

INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1j9Hn6VEAq', 'hot', '⚡博丽灵梦 badapple巡演⚡让东方再次伟大', '永远の蓬莱neet', 9666303, 683924, 717, 17230, '2:24', '日常', 1791158886, 'https://i0.hdslb.com/bfs/archive/f3aff84a9f2f3a2986c2dd1f9d65fab5a1e3d454.jpg', '幻想乡有劲儿的少女们 图包作品交流扣裙：1021325171', 'bilibili', 6, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1Ws411o73M', 'hot', '(删游戏向)东方红魔乡L难度现存最好nmnb纪录', '曼丽之心-Bin', 432110, 393519, 4645, 5727, '25:0', '单机游戏', 1381276701, 'https://i2.hdslb.com/bfs/archive/629e6b620c6aa8db6d0ff96f0756a60e540cb600.jpg', '皇家烈焰世界rep纪录并自制 截止到2013年10月8日，机师SOC，特殊挑战：no miss no bomb 完成于2012年7月28日。东方红魔乡02年的作品，直到2012年才有nmnb的纪录rep出现，玩家是soc.另外也是分数最高的nmnb，然后在同一天，另一位机师clio也跟风似的完成了nmnb。同一天完成还真是。soc玩着还刷了3亿多分，clio打得略为谨慎，红魔乡难掌控，详情请看视频', 'bilibili', 7, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1Bs411f7f8', 'hot', '【東方】超幻想乡级的弹丸论破 （更新至Part24）', '幻想乡的新月', 149592, 365906, 71929, 16930, '1265:2', '动画综合', 1376188169, 'https://i1.hdslb.com/bfs/archive/406cfe77987f968ff6024582da7f6da8ea55cad0.jpg', 'sm21564492 超幻想乡的弹丸论破 更新Part24~ NOH：久 等 了 ， 求 原 谅 。 以下作者提供的证物/人物/规则等卡片（更新）： http://pan.baidu.com/s/1hq3wKHA 密码: yytt 列表：mylist207925', 'bilibili', 8, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1Hs411o7m2', 'hot', '(删游戏向)东方永夜抄B线L难度现存最早国人挑战nmnb全卡纪录', '曼丽之心-Bin', 432110, 351495, 4106, 3987, '42:2', '单机游戏', 1382838293, 'https://i0.hdslb.com/bfs/archive/121887f204cbc77232b11d28c9d42da6349a2e77.jpg', '皇家烈焰rep纪录 （截止到2013年10月26日）机师：YZ，又称：蓬莱の魚の形。作为国人的nmnb全卡纪录，完成于2012年2月8日。在永夜抄里，比国外nmnb大神水月和soc还要早10个月完成（水月和soc是同一天完成的，2012年12月21日）。是不是最早不清楚。既然是国人当然支持了。这作系统信息量大，技巧略多,符卡量较多,练习量较大，据说机师打了2000多小时！详情请看视频。注意辉夜战开', 'bilibili', 9, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV19UPrzvEWL', 'hot', '【东方幻想万华镜】全20话 超清中字', '花大叔Baymax', 400112035, 288621, 2414, 17059, '413:2', '动画综合', 1772782200, 'https://i1.hdslb.com/bfs/archive/59578e48ec125fb7f52ac37676fe162b9679f021.jpg', '年度大会员每月可以白嫖5B币券，想支持我的话可以用这个券充电支持 https://account.bilibili.com/account/big/myPackage', 'bilibili', 10, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;

-- 验证：
--   SELECT COUNT(*) FROM hot_videos WHERE board = 'hot';
