-- ============================================================================
-- 热搜数据 · 历史热门榜 · 第 4/4 块（Day 17）
-- ============================================================================
-- 本块 5 条，全部来自 db/seed-hot.sql（由 db/sync_hot.py 生成）
-- 幂等：ON CONFLICT (bvid) DO UPDATE，重复执行不报错
-- 各块之间没有依赖，可以任意顺序执行
-- ============================================================================

INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1Gs411M7yw', 'hot', '东方永夜抄 Lunatic 全机体无接关通关', '木天明', 328609294, 171470, 543, 1930, '244:32', '单机游戏', 1534234592, 'https://i0.hdslb.com/bfs/archive/8bffa88f896375e3ad9f40721ec7b6384b70e824.jpg', '木天明的个人空间 https://space.bilibili.com/328609294/#/ 东方永夜抄 Lunatic 全单机无接关通关 https://www.bilibili.com/video/av33050590/', 'bilibili', 16, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1Bh411y7kG', 'hot', '东方红魔乡全bgm收集+角色图', '蒲风千晴', 419740037, 164720, 368, 3469, '57:44', '电台', 1611319138, 'https://i0.hdslb.com/bfs/archive/b089e9c64bb36214862b11db90b992d392668f34.jpg', '东方红魔乡全音乐收集，达成', 'bilibili', 17, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1S3CnBmE9m', 'hot', '【东方MMD】大乳の博丽灵梦#6｜Girls', '千代敏儿', 343896757, 129504, 80, 8610, '4:4', 'MMD·3D', 1762955710, 'https://i1.hdslb.com/bfs/archive/b554453ea47142741e88f45ba11705352e74069d.jpg', '【原网址】https://www.youtube.com/watch?v=SuvFZFSN0xk', 'bilibili', 18, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV12jSUBzE6D', 'hot', '“此生无悔入东方，来世愿生幻想乡”', '超耶小曲', 22584841, 96466, 266, 6179, '46:37', '音乐综合', 1775444400, 'https://i1.hdslb.com/bfs/archive/4288722509471f36eb4c9b5900b937c74b577ad3.jpg', '', 'bilibili', 19, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1Nx411w7hH', 'hot', '东方红魔乡最高分欣赏(Lunatic 梦B + Extra 魔B)', 'AliceLast', 65061, 94138, 2203, 1288, '43:56', '单机游戏', 1319112515, 'https://i2.hdslb.com/bfs/archive/699650abb5d5cfa8810f0f19893800b608123aa8.jpg', '自录 分别为miruku氏于今年3月完成的Lunatic rank rep与OOSAKA氏于今年8月完成的Extra rank rep。这两位玩家分别以不同的难度，不断冲击红魔乡的最高分，目前最高分为Extra rank下（即p3） 红魔乡是东方系列在pc win平台上的第一作，系统与之后的所有作有较大不同。整个故事我不再过多评述，传说的开端。也是我ac，bili id的来源。', 'bilibili', 20, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;

-- 验证：
--   SELECT COUNT(*) FROM hot_videos WHERE board = 'hot';
