-- ============================================================================
-- 热搜数据 · 历史热门榜 · 第 1/4 块（Day 17）
-- ============================================================================
-- 本块 5 条，全部来自 db/seed-hot.sql（由 db/sync_hot.py 生成）
-- 幂等：ON CONFLICT (bvid) DO UPDATE，重复执行不报错
-- 各块之间没有依赖，可以任意顺序执行
-- ============================================================================

INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1xx411c79H', 'hot', '【東方】Bad Apple!! ＰＶ【影絵】', '折射', 37, 16282069, 193412, 681393, '3:39', '同人·手书', 1256995125, 'https://i1.hdslb.com/bfs/archive/753453a776fca838165a52c7511e8557857b61ea.jpg', 'sm8628149 2011/9/25追记：大家如果看到空耳字幕请果断举报，净化弹幕环境，你我有责，感谢。', 'bilibili', 1, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1Ms411m7Pf', 'hot', '【东方原曲合集】正作、旧作、官方专辑共793P【5/29更新东方虹龙洞】', 'Josany', 1730160, 3639740, 64892, 80226, '2875:57', '音乐综合', 1438671753, 'https://i2.hdslb.com/bfs/archive/30146c57114aac5f2f0efa4cc96302b68ea4a8e9.jpg', '正作、旧作修复整理完毕，开始官方专辑的修复。 绝大部分的翻译来自THB：http://thwiki.cc/ 5/29更新东方虹龙洞 12/14修复凭依华 8/13完整更新东方鬼形兽 9/2新作秘封噩梦日记 7/31补求闻史记 3/8修补一个问题P+补梦月抄 1.23完成凭依华的更新 10.23修补幺乐团+修复文字错误 8.25增加天空璋翻译 8.13更新天空璋正式版 7.20修复魔理沙的魔法书 7', 'bilibili', 2, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1VuZ5YjEin', 'hot', '【高清修复】东方幻想万华镜全集', 'NyanCatda', 182739766, 3305899, 76141, 214110, '387:52', '动画综合', 1743079127, 'https://i0.hdslb.com/bfs/archive/053e94cdc199c02e143420912cc395ce07666657.jpg', '网络 东方幻想万华镜，部分素材来自http://manpukujinja.blog135.fc2.com/ 都修复到4K了 加了一些正作片段', 'bilibili', 3, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1Bx411P75z', 'hot', '【东方MMD】早苗的推理『上吊的奇迹』【前篇+后篇】', '幻想乡的新月', 149592, 942935, 984, 7679, '10:51', 'MMD·3D', 1414931708, 'https://i2.hdslb.com/bfs/archive/c6df2988cd646be2248bd9f8c64541ba91c9a563.jpg', '恩，这个应该是名侦探早苗的系列吧，嘛~反正都是hentai无所谓啦╮(╯▽╰)╭', 'bilibili', 4, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV13ZbT6UEo5', 'hot', '【东方动画】热情高唱～芙兰朵露和她的小fumo', '幻想乡的新月', 149592, 753023, 182, 45649, '0:12', '动画综合', 1788789850, 'https://i2.hdslb.com/bfs/archive/72119381ba6199405ead3e468912eb7b72904424.jpg', 'https://www.youtube.com/watch?v=yle5VARnkk4 原音频：BV1ZXmcBQEVf 根据这个音频的手书二创：BV1NRun6bEU8 根据这个二创再创造的，就是你现在看到的这个视频 作者PhanthakanXD:我本来想把这个发成短视频的，但不知怎的，很多人都没看到芙兰的可爱，所以我决定改成16:9了 作者的油管频道：https://www.youtube.c', 'bilibili', 5, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;

-- 验证：
--   SELECT COUNT(*) FROM hot_videos WHERE board = 'hot';
