-- ============================================================================
-- 东方同人搜索 · 热搜同步数据 · 当日新发布榜（Day 17）
-- ============================================================================
-- 本文件由 db/sync_hot.py 生成的 db/seed-hot.sql 拆分而来，请勿手工编辑。
-- 数据源：B 站搜索接口（wbi 签名）· 相关性过滤
-- 条数：20
-- 执行前提：先建好 hot_videos 表（db/schema-hot.sql）
-- 幂等：ON CONFLICT (bvid) DO UPDATE，可重复执行不报错
-- ============================================================================

INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1wXpY6xE7M', 'fresh', '东方风神录 东风谷早苗HNN', '藤导磁', 690922530, 0, 0, 0, '2:4', '单机游戏', 1791599996, 'https://i1.hdslb.com/bfs/archive/03bfbbd82f74140ef55ab9606230a18eec1e4120.jpg', '', 'bilibili', 1, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1fFpe6SENM', 'fresh', '东方绀珠传Lunatic 早苗10MNB', '記憶偽筆', 67808865, 1, 0, 0, '33:43', '单机游戏', 1791599788, 'https://i0.hdslb.com/bfs/archive/7d6379451ee31aedc6d31d06263fa9a998ac2836.jpg', '', 'bilibili', 2, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1owpe6EE4v', 'fresh', '[武汉tho]可观测宇宙内阿麟浓度最高的地方', '阿卡麟不会被遗忘', 170209535, 30, 0, 0, '0:26', 'MMD·3D', 1791599257, 'https://i0.hdslb.com/bfs/archive/471d44d7c7120d27fe49d9498352dab708bd4fb9.jpg', '-', 'bilibili', 3, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1xhHX6EE3b', 'fresh', '特异Fumo', '五十五开尔文', 700476417, 5, 0, 0, '0:16', 'MV', 1791598200, 'https://i0.hdslb.com/bfs/archive/75b50478bcc20d0bd5d8c2079d209f4508fafd19.jpg', '-', 'bilibili', 4, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1y8pe6FExJ', 'fresh', '【苏州THO】各种杂项存货（无人机飞行&自由舞台）', '蓬莱山辉夜の玉枝', 412954490, 13, 0, 1, '5:30', '搞笑', 1791598139, 'https://i0.hdslb.com/bfs/archive/a35467b262822c8a577a1d8b6f37df73f7f3a0bc.jpg', '2024年的事情了，当时还是在平江府而不是金陵雅X酒店', 'bilibili', 5, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV13Wpb6fEi2', 'fresh', '魂魄妖梦 全符卡 中间禁移动 全避无伤公式演示', '差错之鱼undyne', 397685732, 64, 0, 0, '8:33', '单机游戏', 1791597600, 'https://i1.hdslb.com/bfs/archive/5b3744bc9bcae6d9ed2ef9f6e4b9df7b8259dbb9.jpg', '中间禁移动教 最新力作！！！', 'bilibili', 6, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1epph6ME2h', 'fresh', '全乡最强最冷最高人气最聪明妖精——琪露诺 LNN', 'dandelion233', 3546717368617604, 41, 0, 0, '2:47', '单机游戏', 1791594540, 'https://i0.hdslb.com/bfs/archive/ab2687b0c462d209ef5e0fc53d1989e333820d84.jpg', '新典的baka没有经典的冻牛肉台词了呜呜呜——BGM也变得更符合歌名了，没有之前那种“最强”的感觉，反而变成“最可爱”了(笑)——不过真要论实力的话，最强的妖精目前来看应该还是皮丝吧()
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1iMHr6eEo9', 'fresh', '【东方project】天空璋Easy文夏不续关通关', '清ze泽', 696729448, 0, 0, 0, '19:0', '单机游戏', 1791592200, 'https://i1.hdslb.com/bfs/archive/e0093f1d7e440cfa97fe9718ba23234c59b4a542.jpg', '游戏：东方天空璋
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1XMpa6iErH', 'fresh', '[东方红魔乡新典EX]  有一个人前来混关', '浮腻', 3640568, 11, 0, 0, '10:37', '单机游戏', 1791588645, 'https://i2.hdslb.com/bfs/archive/b243ef27a56a61f47447e1a938e327e1c707073c.jpg', '丑陋！打的太丑陋了！', 'bilibili', 9, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV117p86QEkn', 'fresh', '如果芙兰朵露的声音换成乌咪', '蓝色少女琪露诺', 3546916042312290, 59, 0, 0, '1:20', '日常', 1791570039, 'https://i1.hdslb.com/bfs/archive/b8f59c266348063ea742d877659fa8b2a73906bf.jpg', '-', 'bilibili', 10, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV117p86QETH', 'fresh', '幻想乡没有巴士！武汉THO痛车区展览区欣赏，从六轮到两轮都有！', 'Im萨姆', 39507722, 542, 4, 5, '1:51', '单机游戏', 1791569939, 'https://i2.hdslb.com/bfs/archive/021a5c5713585b63f77579312ff8e759b761e115.jpg', '武汉tho痛车区实拍！是由奶茶cos的博丽灵梦御地飞行拍的哦（笑）
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1HTph6EEur', 'fresh', '【东方原作补完计划 - 东方永夜抄】我又被东方永夜抄玩了', '失业の膜法使玳烨', 517829430, 186, 0, 4, '29:40', '单机游戏', 1791562079, 'https://i0.hdslb.com/bfs/archive/1a1dbb4a5d0b44f9a2d263e58f16001923248393.jpg', '求三连
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1TRpt6SEML', 'fresh', '【东方project】村纱水蜜 在夏天让水鬼们全部沉底了，快谢谢我们的船长', '正在沉睡请勿打扰', 3546797119113789, 101, 0, 5, '1:42', '单机游戏', 1791556199, 'https://i0.hdslb.com/bfs/archive/498d6196be671289a0ff29de8d3ca32233b9534e.jpg', '-', 'bilibili', 13, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1oZpb6vEwZ', 'fresh', '【东方MMD】东方红魔乡 PV', '探险家sunrise', 3461568480152156, 257, 0, 16, '1:54', 'MMD·3D', 1791548400, 'https://i2.hdslb.com/bfs/archive/725dafef8c90ff7d8ea41eef392d28df3a751c36.jpg', 'https://www.youtube.com/watch?v=3ef0EAyiUdg', 'bilibili', 14, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1E9pb6uEpm', 'fresh', '【东方MMD】在我的世界中直播的琪露诺', '探险家sunrise', 3461568480152156, 265, 0, 15, '0:44', 'MMD·3D', 1791543600, 'https://i2.hdslb.com/bfs/archive/8ad26dbe5b143a73db1e5207c03a97615e0e6fbc.jpg', 'https://www.youtube.com/watch?v=nb3VZRzU0Ik', 'bilibili', 15, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1sBp46rENf', 'fresh', '忒乐忒乐邦邦娜巴拉尼，卡特克贝贝呗……      植物大战僵尸精华版自制关卡：植僵红魔狂', '饲养员和他的fumo们', 3707023367604668, 403, 3, 7, '18:37', '单机游戏', 1791535414, 'https://i0.hdslb.com/bfs/archive/0fe2c6dec748f0da2df0379e745f8c070a247f79.jpg', 'EX关已做好，基本上就是个BOSS RUSH再加个cos二小姐的无畏者
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1gpp46QEy5', 'fresh', '【東方Vocal】Die Before Me_竹取飛翔 ～ Lunatic Princess × 月まで届け、不死の煙', '三好市民流龍馬', 3282234, 36, 0, 3, '4:22', '音乐综合', 1791534785, 'https://i0.hdslb.com/bfs/archive/fa330417736362c7f649185455b94887f1e22e0e.jpg', 'youtube
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1VJp469EP7', 'fresh', '当红雾散去，我将亲手为这里献上一颗毁灭菇！   植物大战僵尸精华版自制关卡：至福乐土洒下血雨', '饲养员和他的fumo们', 3707023367604668, 169, 0, 2, '5:59', '单机游戏', 1791534395, 'https://i0.hdslb.com/bfs/archive/cc571078b947655cb6bbc41cbdf981ee773cc841.jpg', '威！严！
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1YJp469Evs', 'fresh', '东方红魔乡六面就像：', '钟花束', 487166851, 1372, 3, 35, '0:27', '音乐综合', 1791534119, 'https://i2.hdslb.com/bfs/archive/646b90eb5b4f8d0f4597f301f8eba0481bbe9980.jpg', '感觉副歌太突兀了', 'bilibili', 19, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1sEpt65Ed6', 'fresh', 'しゃきしゃきどんどんぱふぱふべーん!', '圣聆琪露诺', 108913469, 1430, 0, 101, '0:14', '日常', 1791525426, 'https://i1.hdslb.com/bfs/archive/be0ce7b1707d7f55db179865373eb36bb58cda4f.jpg', 'up是录像的（', 'bilibili', 20, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;

-- 清理：只保留本次同步的条目，去掉上一轮旧榜
DELETE FROM hot_videos WHERE board = 'fresh' AND bvid NOT IN (
  'BV1wXpY6xE7M', 'BV1fFpe6SENM', 'BV1owpe6EE4v', 'BV1xhHX6EE3b', 'BV1y8pe6FExJ', 'BV13Wpb6fEi2', 'BV1epph6ME2h', 'BV1iMHr6eEo9', 'BV1XMpa6iErH', 'BV117p86QEkn', 'BV117p86QETH', 'BV1HTph6EEur', 'BV1TRpt6SEML', 'BV1oZpb6vEwZ', 'BV1E9pb6uEpm', 'BV1sBp46rENf', 'BV1gpp46QEy5', 'BV1VJp469EP7', 'BV1YJp469Evs', 'BV1sEpt65Ed6'
);

-- 验证：
--   SELECT COUNT(*) FROM hot_videos WHERE board = 'fresh';   -- 期望 20
