-- ============================================================================
-- 东方同人搜索 · 热搜同步数据（Day 17）
-- ============================================================================
-- 本文件由 db/sync_hot.py 自动生成，请勿手工编辑。
-- 数据源：B 站搜索接口（wbi 签名）· 相关性过滤后分区排序
-- 同步时间：2026-10-10 11:29:49（GMT+8）
-- 条数：40（当日新发布 20 + 历史热门 20）
--
-- 幂等：ON CONFLICT (bvid) DO UPDATE，可重复执行不报错
-- 执行位置：CloudBase 控制台 → SQL 数据库 → SQL 编辑器
-- ============================================================================

-- 依赖 hot_videos 表，见 db/schema-hot.sql（首次执行需先建表）

-- ----------------------------------------------------------------------------
-- 榜单：fresh　共 20 条
-- ----------------------------------------------------------------------------
-- 1. 播35 弹0 · 成都THO11 大地に咲く旋律 一场幻想乡的梦
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1Lvpt6YEex', 'fresh', '成都THO11 大地に咲く旋律 一场幻想乡的梦', '雷电灵风RaidenWind', 435448532, 35, 0, 2, '3:22', '日常', 1791602220, 'https://i1.hdslb.com/bfs/archive/c8e873c79ca04d4aa79457bb9f27cc6b9a76b5dd.jpg', '“喂，灵梦，今天有异变吗？” “没有。” “那我们去哪里？” “……先去吃饭。” 看来今天的幻想乡也一如既往地和平。', 'bilibili', 1, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 2. 播5 弹0 · 【東方ニコカラ】NECRO EFFECT - Masayoshi Minoshi
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1g5pe63EZg', 'fresh', '【東方ニコカラ】NECRO EFFECT - Masayoshi Minoshima/坂上なち', '碇暦', 11901017, 5, 0, 1, '11:8', '翻唱', 1791601425, 'https://i2.hdslb.com/bfs/archive/37bac1a950a89cdab481aa9c121e1d6d6e211cd5.jpg', 'Circle:Alstroemeria Records Arrangement:Masayoshi Minoshima Vocal:坂上なち Lyrics:Haruka Original:少女幻葬 ～ Necro-Fantasy Album:DEGENERATE DANCEHALL', 'bilibili', 2, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 3. 播1 弹0 · 魂魄妖梦 ①符 一式「人之剑」中间禁移动 公式
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV13Wpb6fE79', 'fresh', '魂魄妖梦 ①符 一式「人之剑」中间禁移动 公式', '差错之鱼undyne', 397685732, 1, 0, 1, '0:44', '单机游戏', 1791601200, 'https://i2.hdslb.com/bfs/archive/ad62979920a02885488434afc2903312b89baee3.jpg', '新公式①', 'bilibili', 3, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 4. 播2 弹0 · 东方风神录 东风谷早苗HNN
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1wXpY6xE7M', 'fresh', '东方风神录 东风谷早苗HNN', '藤导磁', 690922530, 2, 0, 1, '2:4', '单机游戏', 1791599996, 'https://i1.hdslb.com/bfs/archive/03bfbbd82f74140ef55ab9606230a18eec1e4120.jpg', '', 'bilibili', 4, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 5. 播16 弹0 · 东方绀珠传Lunatic 早苗10MNB
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1fFpe6SENM', 'fresh', '东方绀珠传Lunatic 早苗10MNB', '記憶偽筆', 67808865, 16, 0, 1, '33:43', '单机游戏', 1791599788, 'https://i0.hdslb.com/bfs/archive/7d6379451ee31aedc6d31d06263fa9a998ac2836.jpg', '', 'bilibili', 5, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 6. 播79 弹0 · [武汉tho]可观测宇宙内阿麟浓度最高的地方
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1owpe6EE4v', 'fresh', '[武汉tho]可观测宇宙内阿麟浓度最高的地方', '阿卡麟不会被遗忘', 170209535, 79, 0, 1, '0:26', 'MMD·3D', 1791599257, 'https://i0.hdslb.com/bfs/archive/471d44d7c7120d27fe49d9498352dab708bd4fb9.jpg', '-', 'bilibili', 6, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 7. 播28 弹0 · 【苏州THO】各种杂项存货（无人机飞行&自由舞台）
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1y8pe6FExJ', 'fresh', '【苏州THO】各种杂项存货（无人机飞行&自由舞台）', '蓬莱山辉夜の玉枝', 412954490, 28, 0, 1, '5:30', '搞笑', 1791598139, 'https://i0.hdslb.com/bfs/archive/a35467b262822c8a577a1d8b6f37df73f7f3a0bc.jpg', '2024年的事情了，当时还是在平江府而不是金陵雅X酒店', 'bilibili', 7, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 8. 播88 弹0 · 魂魄妖梦 全符卡 中间禁移动 全避无伤公式演示
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV13Wpb6fEi2', 'fresh', '魂魄妖梦 全符卡 中间禁移动 全避无伤公式演示', '差错之鱼undyne', 397685732, 88, 0, 0, '8:33', '单机游戏', 1791597600, 'https://i1.hdslb.com/bfs/archive/5b3744bc9bcae6d9ed2ef9f6e4b9df7b8259dbb9.jpg', '中间禁移动教 最新力作！！！', 'bilibili', 8, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 9. 播52 弹0 · 全乡最强最冷最高人气最聪明妖精——琪露诺 LNN
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1epph6ME2h', 'fresh', '全乡最强最冷最高人气最聪明妖精——琪露诺 LNN', 'dandelion233', 3546717368617604, 52, 0, 0, '2:47', '单机游戏', 1791594540, 'https://i0.hdslb.com/bfs/archive/ab2687b0c462d209ef5e0fc53d1989e333820d84.jpg', '新典的baka没有经典的冻牛肉台词了呜呜呜——BGM也变得更符合歌名了，没有之前那种“最强”的感觉，反而变成“最可爱”了(笑)——不过真要论实力的话，最强的妖精目前来看应该还是皮丝吧() 不知道从什么时候开始baka就变成公认底力检测器了，yym和ddc的符都好吃底力，hmx的几张符也挺吃的，嘛，毕竟还是名义上的最强嘛，给点特权很正常 算上baka的好朋友大酱，莉莉白，后续出场的皮丝和拉尔瓦，还有', 'bilibili', 9, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 10. 播17 弹0 · [东方红魔乡新典EX] 有一个人前来混关
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1XMpa6iErH', 'fresh', '[东方红魔乡新典EX] 有一个人前来混关', '浮腻', 3640568, 17, 0, 0, '10:37', '单机游戏', 1791588645, 'https://i2.hdslb.com/bfs/archive/b243ef27a56a61f47447e1a938e327e1c707073c.jpg', '丑陋！打的太丑陋了！', 'bilibili', 10, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 11. 播74 弹0 · 如果芙兰朵露的声音换成乌咪
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV117p86QEkn', 'fresh', '如果芙兰朵露的声音换成乌咪', '蓝色少女琪露诺', 3546916042312290, 74, 0, 0, '1:20', '日常', 1791570039, 'https://i1.hdslb.com/bfs/archive/b8f59c266348063ea742d877659fa8b2a73906bf.jpg', '-', 'bilibili', 11, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 12. 播597 弹5 · 幻想乡没有巴士！武汉THO痛车区展览区欣赏，从六轮到两轮都有！
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV117p86QETH', 'fresh', '幻想乡没有巴士！武汉THO痛车区展览区欣赏，从六轮到两轮都有！', 'Im萨姆', 39507722, 597, 5, 7, '1:51', '单机游戏', 1791569939, 'https://i2.hdslb.com/bfs/archive/021a5c5713585b63f77579312ff8e759b761e115.jpg', '武汉tho痛车区实拍！是由奶茶cos的博丽灵梦御地飞行拍的哦（笑） 由武汉景景有约专线合作的悬挂东方tho限定宣传痛版画的营运旅游专线公交车经过几个月又和大家见面了！版画将保持长期留存！ 其他都是各路东方同好的痛车，请大家欣赏，希望大家喜欢。', 'bilibili', 12, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 13. 播209 弹0 · 【东方原作补完计划 - 东方永夜抄】我又被东方永夜抄玩了
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1HTph6EEur', 'fresh', '【东方原作补完计划 - 东方永夜抄】我又被东方永夜抄玩了', '失业の膜法使玳烨', 517829430, 209, 0, 4, '29:40', '单机游戏', 1791562079, 'https://i0.hdslb.com/bfs/archive/1a1dbb4a5d0b44f9a2d263e58f16001923248393.jpg', '求三连 bgm - Sing, R. Sing! - 幼女幻奏', 'bilibili', 13, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 14. 播102 弹0 · 【东方project】村纱水蜜 在夏天让水鬼们全部沉底了，快谢谢我们的船长
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1TRpt6SEML', 'fresh', '【东方project】村纱水蜜 在夏天让水鬼们全部沉底了，快谢谢我们的船长', '正在沉睡请勿打扰', 3546797119113789, 102, 0, 5, '1:42', '单机游戏', 1791556199, 'https://i0.hdslb.com/bfs/archive/498d6196be671289a0ff29de8d3ca32233b9534e.jpg', '-', 'bilibili', 14, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 15. 播259 弹0 · 【东方MMD】东方红魔乡 PV
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1oZpb6vEwZ', 'fresh', '【东方MMD】东方红魔乡 PV', '探险家sunrise', 3461568480152156, 259, 0, 16, '1:54', 'MMD·3D', 1791548400, 'https://i2.hdslb.com/bfs/archive/725dafef8c90ff7d8ea41eef392d28df3a751c36.jpg', 'https://www.youtube.com/watch?v=3ef0EAyiUdg', 'bilibili', 15, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 16. 播270 弹0 · 【东方MMD】在我的世界中直播的琪露诺
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1E9pb6uEpm', 'fresh', '【东方MMD】在我的世界中直播的琪露诺', '探险家sunrise', 3461568480152156, 270, 0, 15, '0:44', 'MMD·3D', 1791543600, 'https://i2.hdslb.com/bfs/archive/8ad26dbe5b143a73db1e5207c03a97615e0e6fbc.jpg', 'https://www.youtube.com/watch?v=nb3VZRzU0Ik', 'bilibili', 16, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 17. 播416 弹3 · 忒乐忒乐邦邦娜巴拉尼，卡特克贝贝呗…… 植物大战僵尸精华版自制关卡：植僵红魔狂
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1sBp46rENf', 'fresh', '忒乐忒乐邦邦娜巴拉尼，卡特克贝贝呗…… 植物大战僵尸精华版自制关卡：植僵红魔狂', '饲养员和他的fumo们', 3707023367604668, 416, 3, 7, '18:37', '单机游戏', 1791535414, 'https://i0.hdslb.com/bfs/archive/0fe2c6dec748f0da2df0379e745f8c070a247f79.jpg', 'EX关已做好，基本上就是个BOSS RUSH再加个cos二小姐的无畏者 再优化一下其他一些小细节明天就可以发布了', 'bilibili', 17, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 18. 播36 弹0 · 【東方Vocal】Die Before Me_竹取飛翔 ～ Lunatic Pr
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1gpp46QEy5', 'fresh', '【東方Vocal】Die Before Me_竹取飛翔 ～ Lunatic Princess × 月まで届け、不死の煙', '三好市民流龍馬', 3282234, 36, 0, 3, '4:22', '音乐综合', 1791534785, 'https://i0.hdslb.com/bfs/archive/fa330417736362c7f649185455b94887f1e22e0e.jpg', 'youtube www.youtube.com/watch?v=uITvSFufHXQ 原UP：Lunatic Phantasma', 'bilibili', 18, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 19. 播178 弹0 · 当红雾散去，我将亲手为这里献上一颗毁灭菇！ 植物大战僵尸精华版自制关卡：至福乐土
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1VJp469EP7', 'fresh', '当红雾散去，我将亲手为这里献上一颗毁灭菇！ 植物大战僵尸精华版自制关卡：至福乐土洒下血雨', '饲养员和他的fumo们', 3707023367604668, 178, 0, 2, '5:59', '单机游戏', 1791534395, 'https://i0.hdslb.com/bfs/archive/cc571078b947655cb6bbc41cbdf981ee773cc841.jpg', '威！严！ 就当作红魔馆又炸了一回吧', 'bilibili', 19, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 20. 播1385 弹3 · 东方红魔乡六面就像：
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1YJp469Evs', 'fresh', '东方红魔乡六面就像：', '钟花束', 487166851, 1385, 3, 35, '0:27', '音乐综合', 1791534119, 'https://i2.hdslb.com/bfs/archive/646b90eb5b4f8d0f4597f301f8eba0481bbe9980.jpg', '感觉副歌太突兀了', 'bilibili', 20, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;

-- ----------------------------------------------------------------------------
-- 榜单：hot　共 20 条
-- ----------------------------------------------------------------------------
-- 1. 播16282152 弹193412 · 【東方】Bad Apple!! ＰＶ【影絵】
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1xx411c79H', 'hot', '【東方】Bad Apple!! ＰＶ【影絵】', '折射', 37, 16282152, 193412, 681397, '3:39', '同人·手书', 1256995125, 'https://i1.hdslb.com/bfs/archive/753453a776fca838165a52c7511e8557857b61ea.jpg', 'sm8628149 2011/9/25追记：大家如果看到空耳字幕请果断举报，净化弹幕环境，你我有责，感谢。', 'bilibili', 1, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 2. 播3639752 弹64893 · 【东方原曲合集】正作、旧作、官方专辑共793P【5/29更新东方虹龙洞】
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1Ms411m7Pf', 'hot', '【东方原曲合集】正作、旧作、官方专辑共793P【5/29更新东方虹龙洞】', 'Josany', 1730160, 3639752, 64893, 80226, '2875:57', '音乐综合', 1438671753, 'https://i2.hdslb.com/bfs/archive/30146c57114aac5f2f0efa4cc96302b68ea4a8e9.jpg', '正作、旧作修复整理完毕，开始官方专辑的修复。 绝大部分的翻译来自THB：http://thwiki.cc/ 5/29更新东方虹龙洞 12/14修复凭依华 8/13完整更新东方鬼形兽 9/2新作秘封噩梦日记 7/31补求闻史记 3/8修补一个问题P+补梦月抄 1.23完成凭依华的更新 10.23修补幺乐团+修复文字错误 8.25增加天空璋翻译 8.13更新天空璋正式版 7.20修复魔理沙的魔法书 7', 'bilibili', 2, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 3. 播3305961 弹76142 · 【高清修复】东方幻想万华镜全集
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1VuZ5YjEin', 'hot', '【高清修复】东方幻想万华镜全集', 'NyanCatda', 182739766, 3305961, 76142, 214113, '387:52', '动画综合', 1743079127, 'https://i0.hdslb.com/bfs/archive/053e94cdc199c02e143420912cc395ce07666657.jpg', '网络 东方幻想万华镜，部分素材来自http://manpukujinja.blog135.fc2.com/ 都修复到4K了 加了一些正作片段', 'bilibili', 3, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 4. 播1552607 弹17143 · 【合集】猩猩也能懂的东方Project
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1XW411b7gT', 'hot', '【合集】猩猩也能懂的东方Project', 'Z一LGW', 11007230, 1552607, 17143, 93639, '647:2', '动画综合', 1513508997, 'https://i1.hdslb.com/bfs/archive/6ed268af331dbbbd1abd87b0a995425324e6067b.jpg', '幻想，依托于现实，但又高于现实。 个人介绍：cv602189（含资助方式） 观看指南：cv113920', 'bilibili', 4, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 5. 播1224307 弹4197 · 东方project人气最高的二十首神曲，你是否有所耳闻？？
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1xW4y1R7HL', 'hot', '东方project人气最高的二十首神曲，你是否有所耳闻？？', '梦绯世', 106339948, 1224307, 4197, 48307, '43:29', '动画综合', 1685937000, 'https://i2.hdslb.com/bfs/archive/59b37e3e28ba802ef20089a7de590f55174c2bad.jpg', '求推荐，求推荐！！ 排名依照网易云QQ酷狗评论数之和进行排名，取前20名（数据盘点时间2023年6月1日） 歌曲评论数在一定程度上相对客观的反应音乐和作品的热度和人气，但数据统计排名仅提供参考（你心中的第一才是真正的第一）不包括纯音乐 审核辛苦了！统一配置的字幕，制作不易，喜欢的朋友，望三连支持下', 'bilibili', 5, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 6. 播1044342 弹928 · 東方是啥？为什么现在不火了？【二次元简史15】
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1k14y1S7gH', 'hot', '東方是啥？为什么现在不火了？【二次元简史15】', '狸林奥菲兽', 3319021, 1044342, 928, 23404, '8:3', '动漫杂谈', 1686916800, 'https://i1.hdslb.com/bfs/archive/8a97774b4f6d0f7be9afb2886c22d3e53f4b3fa1.jpg', '视频中所有BGM都出自东方的官方或同人作品，有些可能大家很熟悉，因为被营销号用烂了（恼）', 'bilibili', 6, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 7. 播942937 弹984 · 【东方MMD】早苗的推理『上吊的奇迹』【前篇+后篇】
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1Bx411P75z', 'hot', '【东方MMD】早苗的推理『上吊的奇迹』【前篇+后篇】', '幻想乡的新月', 149592, 942937, 984, 7679, '10:51', 'MMD·3D', 1414931708, 'https://i2.hdslb.com/bfs/archive/c6df2988cd646be2248bd9f8c64541ba91c9a563.jpg', '恩，这个应该是名侦探早苗的系列吧，嘛~反正都是hentai无所谓啦╮(╯▽╰)╭', 'bilibili', 7, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 8. 播869997 弹1857 · 【补档】【东方科普视频】从零开始入坑的东方project（基础篇（有些大佬也不一
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1jX4y167CW', 'hot', '【补档】【东方科普视频】从零开始入坑的东方project（基础篇（有些大佬也不一定知道的基础~））', '東雲Kukono', 1708147571, 869997, 1857, 56370, '20:9', '动漫杂谈', 1682073780, 'https://i0.hdslb.com/bfs/archive/26de1c2f3124652032ea63a857d8a59de6bcf998.jpg', 'AV840482199 原简介：一个科普东方各种官方作品以及基础的同人作品的视频，可以当作萌新入坑或者是大佬复习的索引，觉得视频做的还可以的可以留个弹幕给UP加加油~~~ 计划了两年多（其中鸽了两年多）的一个视频，也算是为当初的失约补个交代，给当初答应过的up主道个歉。 原作者：@爱摆烂的苹果 侵权必删', 'bilibili', 8, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 9. 播753431 弹182 · 【东方动画】热情高唱～芙兰朵露和她的小fumo
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV13ZbT6UEo5', 'hot', '【东方动画】热情高唱～芙兰朵露和她的小fumo', '幻想乡的新月', 149592, 753431, 182, 45670, '0:12', '动画综合', 1788789850, 'https://i2.hdslb.com/bfs/archive/72119381ba6199405ead3e468912eb7b72904424.jpg', 'https://www.youtube.com/watch?v=yle5VARnkk4 原音频：BV1ZXmcBQEVf 根据这个音频的手书二创：BV1NRun6bEU8 根据这个二创再创造的，就是你现在看到的这个视频 作者PhanthakanXD:我本来想把这个发成短视频的，但不知怎的，很多人都没看到芙兰的可爱，所以我决定改成16:9了 作者的油管频道：https://www.youtube.c', 'bilibili', 9, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 10. 播708296 弹1881 · 【中文CC字幕】【ワンダーランズ×ショウタイム × 初音ミク × KAITO】东
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1TyVwzMEDN', 'hot', '【中文CC字幕】【ワンダーランズ×ショウタイム × 初音ミク × KAITO】东方☆Wonderland【2DMV／世界计划×东方project 联动曲】', 'Project_SEKAI资讯站', 13148307, 708296, 1881, 29907, '3:58', 'VOCALOID·UTAU', 1746350921, 'https://i2.hdslb.com/bfs/archive/089f6efefe8fabeac719a920011e65bcf83239dc.jpg', 'https://youtu.be/iIuZk3Ms1So 歌：ワンダーランズ×ショウタイム × 初音ミク with KAITO 作詞：ビートまりお×まろん 作曲：ZUN (上海アリス幻樂団) 編曲：ビートまりお×まろん、東京アクティブNEETs https://x.com/beatmario https://x.com/maron47 原曲：幽霊楽団　～ Phantom Ensemble 原作：東', 'bilibili', 10, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 11. 播684852 弹717 · ⚡博丽灵梦 badapple巡演⚡让东方再次伟大
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1j9Hn6VEAq', 'hot', '⚡博丽灵梦 badapple巡演⚡让东方再次伟大', '永远の蓬莱neet', 9666303, 684852, 717, 17260, '2:24', '日常', 1791158886, 'https://i0.hdslb.com/bfs/archive/f3aff84a9f2f3a2986c2dd1f9d65fab5a1e3d454.jpg', '幻想乡有劲儿的少女们 图包作品交流扣裙：1021325171', 'bilibili', 11, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 12. 播393520 弹4645 · (删游戏向)东方红魔乡L难度现存最好nmnb纪录
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1Ws411o73M', 'hot', '(删游戏向)东方红魔乡L难度现存最好nmnb纪录', '曼丽之心-Bin', 432110, 393520, 4645, 5727, '25:0', '单机游戏', 1381276701, 'https://i2.hdslb.com/bfs/archive/629e6b620c6aa8db6d0ff96f0756a60e540cb600.jpg', '皇家烈焰世界rep纪录并自制 截止到2013年10月8日，机师SOC，特殊挑战：no miss no bomb 完成于2012年7月28日。东方红魔乡02年的作品，直到2012年才有nmnb的纪录rep出现，玩家是soc.另外也是分数最高的nmnb，然后在同一天，另一位机师clio也跟风似的完成了nmnb。同一天完成还真是。soc玩着还刷了3亿多分，clio打得略为谨慎，红魔乡难掌控，详情请看视频', 'bilibili', 12, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 13. 播365906 弹71929 · 【東方】超幻想乡级的弹丸论破 （更新至Part24）
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1Bs411f7f8', 'hot', '【東方】超幻想乡级的弹丸论破 （更新至Part24）', '幻想乡的新月', 149592, 365906, 71929, 16930, '1265:2', '动画综合', 1376188169, 'https://i1.hdslb.com/bfs/archive/406cfe77987f968ff6024582da7f6da8ea55cad0.jpg', 'sm21564492 超幻想乡的弹丸论破 更新Part24~ NOH：久 等 了 ， 求 原 谅 。 以下作者提供的证物/人物/规则等卡片（更新）： http://pan.baidu.com/s/1hq3wKHA 密码: yytt 列表：mylist207925', 'bilibili', 13, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 14. 播351495 弹4106 · (删游戏向)东方永夜抄B线L难度现存最早国人挑战nmnb全卡纪录
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1Hs411o7m2', 'hot', '(删游戏向)东方永夜抄B线L难度现存最早国人挑战nmnb全卡纪录', '曼丽之心-Bin', 432110, 351495, 4106, 3987, '42:2', '单机游戏', 1382838293, 'https://i0.hdslb.com/bfs/archive/121887f204cbc77232b11d28c9d42da6349a2e77.jpg', '皇家烈焰rep纪录 （截止到2013年10月26日）机师：YZ，又称：蓬莱の魚の形。作为国人的nmnb全卡纪录，完成于2012年2月8日。在永夜抄里，比国外nmnb大神水月和soc还要早10个月完成（水月和soc是同一天完成的，2012年12月21日）。是不是最早不清楚。既然是国人当然支持了。这作系统信息量大，技巧略多,符卡量较多,练习量较大，据说机师打了2000多小时！详情请看视频。注意辉夜战开', 'bilibili', 14, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 15. 播288629 弹2414 · 【东方幻想万华镜】全20话 超清中字
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV19UPrzvEWL', 'hot', '【东方幻想万华镜】全20话 超清中字', '花大叔Baymax', 400112035, 288629, 2414, 17059, '413:2', '动画综合', 1772782200, 'https://i1.hdslb.com/bfs/archive/59578e48ec125fb7f52ac37676fe162b9679f021.jpg', '年度大会员每月可以白嫖5B币券，想支持我的话可以用这个券充电支持 https://account.bilibili.com/account/big/myPackage', 'bilibili', 15, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 16. 播273889 弹1754 · 东方绀珠传 Lunatic 灵梦 NMNB
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1eU4y147pZ', 'hot', '东方绀珠传 Lunatic 灵梦 NMNB', '伊吹小秋', 448823, 273889, 1754, 2972, '34:5', '单机游戏', 1611741431, 'https://i1.hdslb.com/bfs/archive/6c425d35350b18b83a688e2177c9e5032132d296.jpg', 'sm37938912 sm37939266 作者：未知 前作→BV1J4411Q7gj （代理投稿） 简介： 全作中数一数二的狂气高难度作品。 终于能够达成了。', 'bilibili', 16, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 17. 播269941 弹373 · 【東方MMD】咲夜 -stickysticky
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1f9gCzhEKn', 'hot', '【東方MMD】咲夜 -stickysticky', 'Silent-Sliver', 28687790, 269941, 373, 19422, '3:34', 'MMD·3D', 1751291231, 'https://i2.hdslb.com/bfs/archive/c51c9963e16b092e562d63a21ab31c62691d6c96.jpg', '可以限流，就算限流到只有关注我的粉丝才能看到也可以，但请至少让我过审，谢谢，B站有未成年模式，我的视频不会对其有影响的', 'bilibili', 17, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 18. 播257986 弹2429 · 東方永夜抄 Last World模式 全符卡欣赏
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV16x411c7Mn', 'hot', '東方永夜抄 Last World模式 全符卡欣赏', 'bili游客', 55630, 257986, 2429, 4865, '12:47', '单机游戏', 1293372708, 'https://i2.hdslb.com/bfs/archive/776a446e66581ceecd77470ce6384b971925d1e2.jpg', 'sm13135415 由于怕压渣了，就直接上传了，也许会有点卡……温馨小提示【视频时长12：47，右键低品质推荐】', 'bilibili', 18, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 19. 播198859 弹1605 · 【东方红魔乡】原作全剧情+对话
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1ws411A7BC', 'hot', '【东方红魔乡】原作全剧情+对话', '南极冻鱼', 69768372, 198859, 1605, 8479, '22:44', '单机游戏', 1532611143, 'https://i0.hdslb.com/bfs/archive/8a008908d0297bf3699c9b8ca20e2b1ea9145f6c.jpg', '(无结局) 幻想乡迎来了未曾预料的热闹日子。 在神秘的来访者看来，好像连夏天的亡灵都会迷惘。 就在那样的很普通的夏天。 边境被红色的幻想包围了。 * 前言和人物介绍来自游戏自带文案 * 初次投稿 有不对的地方请指出TAT', 'bilibili', 19, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;
-- 20. 播188476 弹90 · 【東方MMD】⑩裙子捕食
INSERT INTO hot_videos (bvid, board, title, author, mid, play, danmaku, favorites, duration, typename, pubdate, cover, description, source, rank_no, synced_at) VALUES ('BV1aoqQBdEws', 'hot', '【東方MMD】⑩裙子捕食', '肉胖胖萝莉', 3546940790802977, 188476, 90, 9161, '0:34', 'MMD·3D', 1766068928, 'https://i0.hdslb.com/bfs/archive/e617fa17107c023c327ae1021be294d058d81428.jpg', 'https://www.nicovideo.jp/watch/sm40768223 作者Aluda', 'bilibili', 20, NOW()) ON CONFLICT (bvid) DO UPDATE SET board = EXCLUDED.board, title = EXCLUDED.title, author = EXCLUDED.author, play = EXCLUDED.play, danmaku = EXCLUDED.danmaku, favorites = EXCLUDED.favorites, pubdate = EXCLUDED.pubdate, cover = EXCLUDED.cover, description = EXCLUDED.description, rank_no = EXCLUDED.rank_no, synced_at = EXCLUDED.synced_at;

-- 只保留本次同步到的条目，清掉上一轮的旧榜（避免榜单越滚越长）
DELETE FROM hot_videos WHERE bvid NOT IN ('BV1Lvpt6YEex', 'BV1g5pe63EZg', 'BV13Wpb6fE79', 'BV1wXpY6xE7M', 'BV1fFpe6SENM', 'BV1owpe6EE4v', 'BV1y8pe6FExJ', 'BV13Wpb6fEi2', 'BV1epph6ME2h', 'BV1XMpa6iErH', 'BV117p86QEkn', 'BV117p86QETH', 'BV1HTph6EEur', 'BV1TRpt6SEML', 'BV1oZpb6vEwZ', 'BV1E9pb6uEpm', 'BV1sBp46rENf', 'BV1gpp46QEy5', 'BV1VJp469EP7', 'BV1YJp469Evs', 'BV1xx411c79H', 'BV1Ms411m7Pf', 'BV1VuZ5YjEin', 'BV1XW411b7gT', 'BV1xW4y1R7HL', 'BV1k14y1S7gH', 'BV1Bx411P75z', 'BV1jX4y167CW', 'BV13ZbT6UEo5', 'BV1TyVwzMEDN', 'BV1j9Hn6VEAq', 'BV1Ws411o73M', 'BV1Bs411f7f8', 'BV1Hs411o7m2', 'BV19UPrzvEWL', 'BV1eU4y147pZ', 'BV1f9gCzhEKn', 'BV16x411c7Mn', 'BV1ws411A7BC', 'BV1aoqQBdEws');

-- 验证：
--   SELECT COUNT(*) FROM hot_videos;                          -- 期望 40
--   SELECT board, COUNT(*) FROM hot_videos GROUP BY board;    -- fresh/hot 各若干
--   SELECT rank_no, play, title FROM hot_videos WHERE board = 
--     'fresh' ORDER BY rank_no LIMIT 5;

